// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjflfyglzmquqjfovcmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZmxmeWdsem1xdXFqZm92Y21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTgwNDksImV4cCI6MjA2MTczNDA0OX0.gJnx1agaTMaWYIMptm1n_d5Uu2d5YYVmYt1GIJBs3_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);